services:
  # NestJS Application (Production)
  # Conecta a DATABASE_URL (Render) en lugar de postgres local
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: backlog-pro-backend:prod
    env_file:
      - .env.production
    ports:
      - '${PORT:-3002}:${PORT:-3000}'
    restart: always
    healthcheck:
      test: >
        curl --fail --silent http://localhost:${PORT:-3002}/healthz
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Base de Datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-backlog_pro}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5434}:${DB_PORT:-5432}'
    restart: unless-stopped
    healthcheck:
      test: > 
        pg_isready -h localhost -U ${DB_USERNAME:-postgres}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Adminer - Herramienta web para gestionar la base de datos
  adminer:
    image: adminer:latest
    ports:
      - '8081:8080'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    healthcheck:
      test: > 
        curl --fail --silent http://localhost:8080
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
      driver: local
