services:
  # Backlog Pro Backend - usando imagen de DockerHub
  app:
    image: ${DOCKER_USERNAME}/backlog-pro-backend:latest
    ports:
      - '${PORT:-3000}:3000'
    environment:
      # Configuración del Servidor
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000

      # Configuración de la Base de Datos (PostgreSQL)
      DB_HOST: postgres # Nombre del servicio en docker-compose
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_DATABASE: ${DB_DATABASE:-backlog_pro}

      # Configuración JWT
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}

      # Hot reload para Windows/Docker
      CHOKIDAR_USEPOLLING: 'true'

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backlog-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/graphql']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de Datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-backlog_pro}
    volumes:
      # Persistir datos de la base de datos
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Exponer PostgreSQL para acceso en desarrollo local
      - '${DB_PORT:-5432}:5432'
    networks:
      - backlog-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-backlog_pro}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backlog-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
